daos-stack/google-cloud-daos

- images/configs/daos_agent.yml
- images/configs/daos_control.yml
- images/configs/daos_server.yml
Remove license header from yaml config files.
Use "engines:" instead of "servers:" in daos_server.yml.
Bump crt_timeout to 200s
Signed-off-by: Johann Lombardi <johann.lombardi@intel.com>
> Adjust DAOS yaml config file

- examples/daos_client_mig/README.md
- examples/simple_daos_server_example/README.md
- images/README.md
- images/scripts/install-client.sh
- images/scripts/install.sh
- modules/daos_client/README.md
- modules/daos_server/README.md
$ nvme get-feature /dev/nvme0 -f 7
get-feature:0x7 (Number of Queues), Current value:00000000
Value is 00000000 which means that this SSD is reporting it only
has 1 qpair (1 submission queue and 1 completion queue).
Backport a SPDK patch to work around this issue.
Remove leftover from 1.1.4 and license from README file.
Install updated SPDK RPMs with workaround for NVMe bug
Signed-off-by: Johann Lombardi <johann.lombardi@intel.com>
> Update SPDK RPMs to work around NVMe get-feature issue

- .gitignore
- images/daos-client-image.json
- images/scripts/install.sh
- images/scripts/io500_install.sh
- images/scripts/mfu_install.sh
Initial commit that installs the mpi file utils (mfu) and other
dependencies for the io500 workload into the DAOS client image.
Dependencies are installed into /usr/local/io500
Signed-off-by: Joel Rosenzweig <joel.b.rosenzweig@intel.com>
Signed-off-by: Johann Lombardi <johann.lombardi@intel.com>
> Build and install IO500 in client image

- terraform/examples/io500/setup_io500.sh
- terraform/examples/io500/start.sh
> Speedup deployment and propagate SSH keys on client nodes

- terraform/examples/io500/configure.sh
- terraform/examples/io500/run_io500-sc21.sh
This fixes a bug introduced in PR#9 that causes the run_io500-sc21.sh
script to fail in a 1 server 1 client configuration.
> DAOS-9673 Fix for 1 server 1 client error in IO500 example

- terraform/examples/io500/start.sh
I had trouble using the io500 start.sh scripts
The following changes were needed to get things into
a working state.
With this and some firewall/proxy changes I can use the io500 build 
scripts in my GCP project. 
Signed-off-by: Keith Mannthey<keith.mannthey@intel.com>
> Add zone info to a few gcloud commands

- terraform/examples/daos_cluster/README.md
- terraform/examples/daos_cluster/main.tf
- terraform/examples/daos_cluster/module.json
- terraform/examples/daos_cluster/terraform.tfvars.perf.example
- terraform/examples/daos_cluster/terraform.tfvars.tco.example
- terraform/examples/daos_cluster/variables.tf
- terraform/examples/only_daos_client/README.md
- terraform/examples/only_daos_client/main.tf
- terraform/examples/only_daos_client/module.json
- terraform/examples/only_daos_client/terraform.tfvars.example
- terraform/examples/only_daos_client/variables.tf
- terraform/examples/only_daos_server/README.md
- terraform/examples/only_daos_server/main.tf
- terraform/examples/only_daos_server/module.json
- terraform/examples/only_daos_server/terraform.tfvars.perf.example
- terraform/examples/only_daos_server/terraform.tfvars.tco.example
- terraform/examples/only_daos_server/variables.tf
- terraform/modules/daos_client/README.md
- terraform/modules/daos_client/main.tf
- terraform/modules/daos_client/module.json
- terraform/modules/daos_client/variables.tf
- terraform/modules/daos_server/README.md
- terraform/modules/daos_server/main.tf
- terraform/modules/daos_server/module.json
- terraform/modules/daos_server/outputs.tf
- terraform/modules/daos_server/templates/configure_daos.tftpl
- terraform/modules/daos_server/templates/daos_control.yml.tftpl
- terraform/modules/daos_server/variables.tf
The goal is to supporte better integrations and provide a better
customer experience by adding good defaults and default behavior
to the server and client modules (along with the various examples that
depend on them). For now, the server defaults to optimizing for TCO.
> DAOSGCP-82 Changing defaults and default behaviors

- terraform/examples/io500/install_scripts/install_io500-sc21.sh
Fix for a patch to IO500 that was causing IO500 image builds to fail.
> DAOSGCP-94 Fix for io500_prepare.patch

- images/scripts/install_daos.sh
- terraform/examples/daos_cluster/variables.tf
- terraform/modules/daos_server/README.md
- terraform/modules/daos_server/main.tf
- terraform/modules/daos_server/module.json
- terraform/modules/daos_server/outputs.tf
- terraform/modules/daos_server/scripts/daos_client_install_script.sh
> DAOSGCP-85 Add daos_client_install_script output to daos_server module

- images/build_images.sh
- images/daos-client-image.pkr.hcl
- images/daos-server-image.pkr.hcl
The images/build_images.sh script was setting up a firewall rule
to allow port 22 to 0.0.0.0/0.  Packer was then using SSH to
configure the image. Removed the firewall rule and changed packer
to only use an internal IP and then use IAP tunnelling to
log into the instance via SSH.
> DAOSGCP-102 Changed packer scripts to use IAP with private IP

- images/scripts/cert_gen/sm_get_ca.sh
Copy the agent.crt and agent.key files to /etc/daos/certs
on DAOS server instances
> DAOSGCP-103 Copy agent cert files on server instances

- images/daos-client-image.pkr.hcl
- images/daos-server-image.pkr.hcl
* Changing packer so the machine has a public IP addresses, which is
necessary if the customer project does not have a cloud NAT.
* Changing the order of cert steps to increase reliability: chmod before
chown.
Signed-off-by: Carlos Boneti <carlosboneti@google.com>
> DAOSGCP-104 Fix image build issues related to IAP tunneling configuration

- terraform/examples/io500/build_daos_io500_images.sh
- terraform/examples/io500/install_scripts/install_io500-isc22.sh
- terraform/examples/io500/io500-isc22.config-template.daos-rf0.ini
- terraform/examples/io500/run_io500-isc22.sh
- terraform/examples/io500/start.sh
Scripts for installation and running test io500-isc22 (no EC part in this PR)
> DAOSGCP-106 Add io500-isc22  

- images/daos-server-image.pkr.hcl
If
"sudo chmod +x /var/daos/cert_gen/*.sh"
is executed after
"sudo chown -R root:root /var/daos/cert_gen"
then there is no guarantee that the /var/daos/cert_gen/*.sh part is properly expanded. This is because expansion is performed by the shell invoking sudo and not by the command which is run under sudo. If the invoking shell does not have x permission on /var/daos/cert_gen then chmod will be passed the literal string "/var/daos/cert_gen/*.sh" which it will assume to be a valid path, which it is not.
Signed-off-by: Daniel Ahlin <50445206+danielahlin@users.noreply.github.com>
> Swap chmod/chown to fix wildcard expansion error

- README.md
- terraform/examples/daos_cluster/README.md
In preparation for the merge from develop to main
the cloudshell tutorial URLs in the README.md files were updated to point to the main branch.
> DAOSGCP-142 Update cloudshell tutorial URLs

- images/build_images.sh
This fixes the following error while building an image:
```
$ ./build_daos_io500_images.sh -t all -i false -f -w projects/my-project/locations/us-central1/workerPools/build-pool-1
[INFO ] Building DAOS disk images for IO500
[INFO ] Temp directory for image building: /tmp/tmp.QZtFLQeShK
[INFO ] Building DAOS server image: daos-server-io500-centos-7
[INFO ] Building DAOS Image(s)
[INFO ] Packer will be using service account serviceAccount:805869098137@cloudbuild.gserviceaccount.com
[INFO ] Using build worker pool projects/my-project/locations/us-central1/workerPools/build-pool-1, region
[INFO ] Building server image
Creating temporary tarball archive of 12 file(s) totalling 38.5 KiB before compression.
Uploading tarball of [.] to [gs://my-project_cloudbuild/source/1677693367.658952-458724d82 …
```
> DAOSGCP-161 Fix setting the --region parameter

- terraform/examples/daos_cluster/README.md
- terraform/examples/daos_cluster/main.tf
- terraform/examples/daos_cluster/variables.tf
- terraform/examples/io500/start.sh
- terraform/modules/daos_client/README.md
- terraform/modules/daos_client/main.tf
- terraform/modules/daos_client/variables.tf
- terraform/modules/daos_server/README.md
- terraform/modules/daos_server/main.tf
- terraform/modules/daos_server/variables.tf
Remove Managed Instance Group (MIG) provisioning from Terrform modules.
For large deployments provisioning instances with google_compute_instance vs google_compute_instance_group_manager reduces provisioning time.
This change was provided by Margaret Lawson.
Signed-off-by: Margaret Lawson <mlawsonca@google.com>
> DAOSGCP-151 Remove MIGs in Terraform modules

- terraform/examples/io500/client_files/run_io500-sc22.sh
- terraform/modules/daos_client/main.tf
- terraform/modules/daos_server/main.tf
Reducing the number of threads that run on each physical CPU core can help improve the performance of workloads that are highly-parallel.
> DAOSGCP-140 Configure 1 thread per vCPU

- docs/pre-deployment_guide.md
Fixed broken link in predeployment guide.
> DAOSGCP-153 Fixed link in predeployment guide.

- images/ansible_playbooks/tune.yml
- images/daos.pkr.hcl
Recent changes require ansible to be installed with the ansible-core package. That package now uses Python 3.11.
> DAOSGCP-178 Fixes for ansible changes in EPEL

- images/ansible_playbooks/tune.yml
- images/daos.pkr.hcl
- security.md
- terraform/examples/io500/bin/get_io500_result_data.sh
- terraform/examples/io500/bin/start.sh
- terraform/examples/io500/bin/stop.sh
Merge develop to main for the v0.4.1 release
Re-do of PR https://github.com/daos-stack/google-cloud-daos/pull/88 without squashing.
> DAOSGCP-180 Merge develop to main for v0.4.1

- terraform/modules/daos_server/templates/pool_cont_create.inc.sh.tftpl
- terraform/modules/daos_server/templates/storage_format.inc.sh.tftpl
Added a check for the % in the pool.size variable.
If pool.size contains a % character the --tier-ratio option is not used when creating pools.
> DAOSGCP-220 Do not set tier-ratio when pool.size = *%

- terraform/examples/daos_cluster/README.md
- terraform/examples/daos_cluster/main.tf
- terraform/examples/daos_cluster/terraform.tfvars.perf.example
- terraform/examples/daos_cluster/terraform.tfvars.tco.example
- terraform/examples/daos_cluster/variables.tf
- terraform/examples/io500/README.md
- terraform/examples/io500/variables.tf
- terraform/modules/daos_server/README.md
- terraform/modules/daos_server/main.tf
- terraform/modules/daos_server/templates/daos_server.yml.tftpl
- terraform/modules/daos_server/templates/pool_cont_create.inc.sh.tftpl
- terraform/modules/daos_server/variables.tf
Removed variables from examples that specify SCM size.
Removed hugepage settings since that is not needed in DAOS v2.4
> DAOSGCP-222 Remove variables that specify SCM size and hugepages

- terraform/modules/daos_server/scripts/client_install.sh
- terraform/modules/daos_server/templates/daos_agent.yml.tftpl
Added retry logic for daos-* package installs
Commented out hard coded network interface config in daos_client.yml since slurm instances do not force eth0 name for primary ethernet interface.
> DAOSGCP-224 Updates required for HPC Toolkit hpc-slurm6-daos example
