daos-stack/google-cloud-daos

modules/daos_client/main.tf
modules/daos_client/variables.tf
modules/daos_server/main.tf
modules/daos_server/variables.tf

Add the ability to use a preemptible instance

---

terraform/examples/io500/run_io500-sc21.sh

To verify usage imbalance among the targets.
Signed-off-by: Johann Lombardi <johann.lombardi@intel.com>

Query pool at the end of IO500

---

terraform/examples/daos_client_mig/README.md
terraform/examples/daos_client_mig/main.tf
terraform/examples/daos_client_mig/terraform.tfvars.example
terraform/examples/daos_client_mig/variables.tf
terraform/examples/full_cluster_setup/main.tf
terraform/examples/full_cluster_setup/terraform.tfvars.example
terraform/examples/full_cluster_setup/variables.tf
terraform/examples/simple_daos_server_example/README.md
terraform/examples/simple_daos_server_example/main.tf
terraform/examples/simple_daos_server_example/terraform.tfvars.example
terraform/examples/simple_daos_server_example/variables.tf
terraform/modules/daos_client/README.md
terraform/modules/daos_client/main.tf
terraform/modules/daos_client/variables.tf
terraform/modules/daos_server/README.md
terraform/modules/daos_server/main.tf
terraform/modules/daos_server/variables.tf

Updated modules to allow labels on instances.
Updated examples to show how to add labels.

DAOS-9737 Add support for applying labels to instances

---

README.md
terraform/README.md
terraform/examples/README.md
terraform/examples/full_cluster_setup/README.md
terraform/examples/io500/README.md

DAOS-9911 Update documentation

---

terraform/examples/io500/start.sh

DAOSGCP-80 Add functionality to propagate SSH keys to all nodes

---

terraform/examples/io500/config/config.sh
terraform/examples/io500/config/config_1c_1s_8d.sh
terraform/examples/io500/config/config_2c_2s_16d.sh

DAOSGCP-81 Fix the calculation of the pool size

---

terraform/examples/io500/README.md
terraform/examples/io500/config/config.sh
terraform/examples/io500/config/config_1c_1s_8d.sh
terraform/examples/io500/config/config_2c_2s_16d.sh
terraform/examples/io500/start.sh
terraform/examples/io500/stop.sh

DAOSGCP-91 Fix IO500 deployment

---

terraform/examples/io500/install_scripts/install_io500-sc21.sh

DAOSGCP-92 Update IOR to version with fix for mdtest

---

images/build_images.sh

DAOSGCP-96 Add functionality to check GCP permission before adding them

---

terraform/examples/io500/install_scripts/install_intel-oneapi.sh

DAOSGCP-108 Pin intel-oneapi-mpi packages to specific version

---

terraform/examples/daos_cluster/terraform.tfvars.perf.example
terraform/examples/daos_cluster/terraform.tfvars.tco.example
terraform/examples/daos_cluster/variables.tf
terraform/modules/daos_server/templates/pool_cont_create.inc.sh.tftpl
terraform/modules/daos_server/variables.tf

DAOSGCP-83 Add option to set user and group for pool and container

---

images/build_images.sh
images/daos-client-image.pkr.hcl
images/daos-server-image.pkr.hcl
images/packer_cloudbuild-client.yaml
images/packer_cloudbuild-server.yaml
terraform/examples/io500/build_daos_io500_images.sh

Add a new switch --use-iap true|false
Signed-off-by: Dariusz M <damok@google.com>

DAOSGCP-125 Add switch for use_iap in packer scripts

---

images/daos-server-image.pkr.hcl

Signed-off-by: Daniel Ahlin <50445206+danielahlin@users.noreply.github.com>

Swap chmod/chown to fix wildcard expansion error

---

images/scripts/cert_gen/gen_certificates.sh

Update BSD-2-Clause-Patent in images/scripts/cert_gen/gen_certificates.sh I will update the license info in DAOS too.
Signed-off-by: Lei Huang <lei.huang@intel.com>

DAOSGCP-138 Update the license in gen_certificates.sh

---

tools/autodoc/cloudshell_urls.sh

Fix issue that caused failure when running the cloudshell_urls.sh script from the root of the repo.

DAOSGCP-143 Fix issue with git command

---

.pre-commit-config.yaml
terraform/examples/daos_cluster/variables.tf
terraform/examples/daos_cluster/versions.tf
terraform/examples/io500/README.md
terraform/examples/io500/bin/_log.sh
terraform/examples/io500/bin/start.sh
terraform/examples/io500/bin/stop.sh
terraform/examples/io500/client_files/clean_storage.sh
terraform/examples/io500/main.tf
terraform/modules/daos_server/README.md
terraform/modules/daos_server/main.tf
terraform/modules/daos_server/outputs.tf
terraform/modules/daos_server/scripts/client_install.sh
tools/autodoc/addlicense.sh
tools/autodoc/cloudshell_urls.sh

DAOSGCP-159 Update copyright date in comment headers

---

security.md

DAOSGCP-189 Added security.md

---

images/README.md

Corrected example of GCP_USE_CLOUDBUILD value.

DAOSGCP-216 Correction in images/README.md

---

docs/pre-deployment_guide.md

The link was not necessary since the information is provided in the "Creating and managing projects" documentation.

DAOSGCP-183 Removed link to getting-started doc

---

terraform/examples/daos_cluster/versions.tf
terraform/examples/io500/versions.tf
terraform/modules/daos_client/versions.tf
terraform/modules/daos_server/versions.tf

Change provider versions to match versions generated by HPC Toolkit.

DAOSGCP-219 Change provider versions

---

terraform/examples/daos_cluster/README.md
terraform/examples/daos_cluster/main.tf
terraform/examples/daos_cluster/variables.tf
terraform/examples/daos_cluster/versions.tf
terraform/examples/io500/README.md
terraform/examples/io500/client_files/run_io500-sc23.sh
terraform/examples/io500/variables.tf
terraform/examples/io500/versions.tf
terraform/modules/daos_client/README.md
terraform/modules/daos_client/variables.tf
terraform/modules/daos_server/README.md
terraform/modules/daos_server/main.tf
terraform/modules/daos_server/variables.tf

Added tag variables to examples so that firewall rules can be applied to instances

DAOSGCP-221 Add tag variables to examples
